// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: authz/v1/authz.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAuthzServiceGrantPermission = "/authz.v1.AuthzService/GrantPermission"
const OperationAuthzServiceGrantRole = "/authz.v1.AuthzService/GrantRole"
const OperationAuthzServiceRevokeRole = "/authz.v1.AuthzService/RevokeRole"

type AuthzServiceHTTPServer interface {
	GrantPermission(context.Context, *GrantPermissionRequest) (*emptypb.Empty, error)
	GrantRole(context.Context, *GrantRoleRequest) (*emptypb.Empty, error)
	RevokeRole(context.Context, *RevokeRoleRequest) (*emptypb.Empty, error)
}

func RegisterAuthzServiceHTTPServer(s *http.Server, srv AuthzServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/authz/roles", _AuthzService_GrantRole0_HTTP_Handler(srv))
	r.POST("/api/v1/authz/roles/revoke", _AuthzService_RevokeRole0_HTTP_Handler(srv))
	r.POST("/api/v1/authz/permissions", _AuthzService_GrantPermission0_HTTP_Handler(srv))
}

func _AuthzService_GrantRole0_HTTP_Handler(srv AuthzServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GrantRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthzServiceGrantRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GrantRole(ctx, req.(*GrantRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AuthzService_RevokeRole0_HTTP_Handler(srv AuthzServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthzServiceRevokeRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeRole(ctx, req.(*RevokeRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AuthzService_GrantPermission0_HTTP_Handler(srv AuthzServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GrantPermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthzServiceGrantPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GrantPermission(ctx, req.(*GrantPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type AuthzServiceHTTPClient interface {
	GrantPermission(ctx context.Context, req *GrantPermissionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GrantRole(ctx context.Context, req *GrantRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	RevokeRole(ctx context.Context, req *RevokeRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type AuthzServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAuthzServiceHTTPClient(client *http.Client) AuthzServiceHTTPClient {
	return &AuthzServiceHTTPClientImpl{client}
}

func (c *AuthzServiceHTTPClientImpl) GrantPermission(ctx context.Context, in *GrantPermissionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/authz/permissions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthzServiceGrantPermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AuthzServiceHTTPClientImpl) GrantRole(ctx context.Context, in *GrantRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/authz/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthzServiceGrantRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AuthzServiceHTTPClientImpl) RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/authz/roles/revoke"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuthzServiceRevokeRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
