// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authz/v1/authz.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRoleRequest) Reset() {
	*x = GrantRoleRequest{}
	mi := &file_authz_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRoleRequest) ProtoMessage() {}

func (x *GrantRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRoleRequest.ProtoReflect.Descriptor instead.
func (*GrantRoleRequest) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *GrantRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GrantRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RevokeRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_authz_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RevokeRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GrantPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"` // user_id hoặc role
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`   // resource
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`   // action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantPermissionRequest) Reset() {
	*x = GrantPermissionRequest{}
	mi := &file_authz_v1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantPermissionRequest) ProtoMessage() {}

func (x *GrantPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantPermissionRequest.ProtoReflect.Descriptor instead.
func (*GrantPermissionRequest) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *GrantPermissionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GrantPermissionRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *GrantPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_authz_v1_authz_proto protoreflect.FileDescriptor

const file_authz_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x14authz/v1/authz.proto\x12\bauthz.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bbuf/validate/validate.proto\x1a\x19authz/v1/permission.proto\"I\n" +
	"\x10GrantRoleRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n" +
	"\x04role\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04role\"J\n" +
	"\x11RevokeRoleRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n" +
	"\x04role\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04role\"z\n" +
	"\x16GrantPermissionRequest\x12 \n" +
	"\asubject\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\asubject\x12\x1e\n" +
	"\x06object\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06object\x12\x1e\n" +
	"\x06action\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06action2\x9d\x03\n" +
	"\fAuthzService\x12w\n" +
	"\tGrantRole\x12\x1a.authz.v1.GrantRoleRequest\x1a\x16.google.protobuf.Empty\"6\x8a\xb5\x18\x14\n" +
	"\x04role\x12\x05grant\x1a\x05admin\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/authz/roles\x12\x81\x01\n" +
	"\n" +
	"RevokeRole\x12\x1b.authz.v1.RevokeRoleRequest\x1a\x16.google.protobuf.Empty\">\x8a\xb5\x18\x15\n" +
	"\x04role\x12\x06revoke\x1a\x05admin\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/authz/roles/revoke\x12\x8f\x01\n" +
	"\x0fGrantPermission\x12 .authz.v1.GrantPermissionRequest\x1a\x16.google.protobuf.Empty\"B\x8a\xb5\x18\x1a\n" +
	"\n" +
	"permission\x12\x05grant\x1a\x05admin\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/authz/permissionsB\x89\x01\n" +
	"\fcom.authz.v1B\n" +
	"AuthzProtoP\x01Z,github.com/tencat-dev/go-base/api/authz/v1\xa2\x02\x03AXX\xaa\x02\bAuthz.V1\xca\x02\bAuthz\\V1\xe2\x02\x14Authz\\V1\\GPBMetadata\xea\x02\tAuthz::V1b\x06proto3"

var (
	file_authz_v1_authz_proto_rawDescOnce sync.Once
	file_authz_v1_authz_proto_rawDescData []byte
)

func file_authz_v1_authz_proto_rawDescGZIP() []byte {
	file_authz_v1_authz_proto_rawDescOnce.Do(func() {
		file_authz_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authz_v1_authz_proto_rawDesc), len(file_authz_v1_authz_proto_rawDesc)))
	})
	return file_authz_v1_authz_proto_rawDescData
}

var file_authz_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_authz_v1_authz_proto_goTypes = []any{
	(*GrantRoleRequest)(nil),       // 0: authz.v1.GrantRoleRequest
	(*RevokeRoleRequest)(nil),      // 1: authz.v1.RevokeRoleRequest
	(*GrantPermissionRequest)(nil), // 2: authz.v1.GrantPermissionRequest
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_authz_v1_authz_proto_depIdxs = []int32{
	0, // 0: authz.v1.AuthzService.GrantRole:input_type -> authz.v1.GrantRoleRequest
	1, // 1: authz.v1.AuthzService.RevokeRole:input_type -> authz.v1.RevokeRoleRequest
	2, // 2: authz.v1.AuthzService.GrantPermission:input_type -> authz.v1.GrantPermissionRequest
	3, // 3: authz.v1.AuthzService.GrantRole:output_type -> google.protobuf.Empty
	3, // 4: authz.v1.AuthzService.RevokeRole:output_type -> google.protobuf.Empty
	3, // 5: authz.v1.AuthzService.GrantPermission:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authz_v1_authz_proto_init() }
func file_authz_v1_authz_proto_init() {
	if File_authz_v1_authz_proto != nil {
		return
	}
	file_authz_v1_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authz_v1_authz_proto_rawDesc), len(file_authz_v1_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authz_v1_authz_proto_goTypes,
		DependencyIndexes: file_authz_v1_authz_proto_depIdxs,
		MessageInfos:      file_authz_v1_authz_proto_msgTypes,
	}.Build()
	File_authz_v1_authz_proto = out.File
	file_authz_v1_authz_proto_goTypes = nil
	file_authz_v1_authz_proto_depIdxs = nil
}
