// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authz/v1/permission.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionOption) Reset() {
	*x = PermissionOption{}
	mi := &file_authz_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionOption) ProtoMessage() {}

func (x *PermissionOption) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionOption.ProtoReflect.Descriptor instead.
func (*PermissionOption) Descriptor() ([]byte, []int) {
	return file_authz_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionOption) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *PermissionOption) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionOption) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var file_authz_v1_permission_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*PermissionOption)(nil),
		Field:         50001,
		Name:          "authz.v1.permission",
		Tag:           "bytes,50001,opt,name=permission",
		Filename:      "authz/v1/permission.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional authz.v1.PermissionOption permission = 50001;
	E_Permission = &file_authz_v1_permission_proto_extTypes[0]
)

var File_authz_v1_permission_proto protoreflect.FileDescriptor

const file_authz_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x19authz/v1/permission.proto\x12\bauthz.v1\x1a google/protobuf/descriptor.proto\"X\n" +
	"\x10PermissionOption\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles:\\\n" +
	"\n" +
	"permission\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2\x1a.authz.v1.PermissionOptionR\n" +
	"permissionB\x8e\x01\n" +
	"\fcom.authz.v1B\x0fPermissionProtoP\x01Z,github.com/tencat-dev/go-base/api/authz/v1\xa2\x02\x03AXX\xaa\x02\bAuthz.V1\xca\x02\bAuthz\\V1\xe2\x02\x14Authz\\V1\\GPBMetadata\xea\x02\tAuthz::V1b\x06proto3"

var (
	file_authz_v1_permission_proto_rawDescOnce sync.Once
	file_authz_v1_permission_proto_rawDescData []byte
)

func file_authz_v1_permission_proto_rawDescGZIP() []byte {
	file_authz_v1_permission_proto_rawDescOnce.Do(func() {
		file_authz_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authz_v1_permission_proto_rawDesc), len(file_authz_v1_permission_proto_rawDesc)))
	})
	return file_authz_v1_permission_proto_rawDescData
}

var file_authz_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authz_v1_permission_proto_goTypes = []any{
	(*PermissionOption)(nil),           // 0: authz.v1.PermissionOption
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_authz_v1_permission_proto_depIdxs = []int32{
	1, // 0: authz.v1.permission:extendee -> google.protobuf.MethodOptions
	0, // 1: authz.v1.permission:type_name -> authz.v1.PermissionOption
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authz_v1_permission_proto_init() }
func file_authz_v1_permission_proto_init() {
	if File_authz_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authz_v1_permission_proto_rawDesc), len(file_authz_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_authz_v1_permission_proto_goTypes,
		DependencyIndexes: file_authz_v1_permission_proto_depIdxs,
		MessageInfos:      file_authz_v1_permission_proto_msgTypes,
		ExtensionInfos:    file_authz_v1_permission_proto_extTypes,
	}.Build()
	File_authz_v1_permission_proto = out.File
	file_authz_v1_permission_proto_goTypes = nil
	file_authz_v1_permission_proto_depIdxs = nil
}
